# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-07-12 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_auto_20200712_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Genres',
            name='user',
            field=models.ManyToManyField(blank=True, to='users.User', verbose_name='Usuario'),
        ),
    ]
