# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-07-16 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20200716_0303'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tag',
            field=models.ManyToManyField(blank=True, to='tags.Tag', verbose_name='Preferencia'),
        ),
    ]
