# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-13 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_tagaffinity'),
        ('users', '0003_auto_20200913_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tagAffinity',
            field=models.ManyToManyField(blank=True, to='tags.TagAffinity', verbose_name='Affinidad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tag',
            field=models.ManyToManyField(blank=True, to='tags.Tag', verbose_name='Preferencia'),
        ),
    ]
