# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-13 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_tag_affinity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagAffinity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name_affinity', models.CharField(max_length=50, unique=True, verbose_name='Género')),
                ('affinity', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
