# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-14 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_tagaffinity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagaffinity',
            name='tag_name_affinity',
            field=models.CharField(max_length=50, verbose_name='Género'),
        ),
    ]
