# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-07-12 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0003_auto_20200712_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=20, verbose_name='Autor')),
                ('summary', models.CharField(blank=True, max_length=100, verbose_name='Resumen')),
                ('genres', models.ManyToManyField(blank=True, to='genres.Genres', verbose_name='Género')),
            ],
        ),
    ]
