# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-07-16 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(blank=True, max_length=50, verbose_name='Autor')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Título')),
                ('summary', models.CharField(blank=True, max_length=100, verbose_name='Resumen')),
                ('goodreads_book_id', models.IntegerField(blank=True, null=True)),
                ('best_book_id', models.IntegerField(blank=True, null=True)),
                ('work_id', models.IntegerField(blank=True, null=True)),
                ('books_count', models.IntegerField(blank=True, null=True)),
                ('isbn', models.IntegerField(blank=True, null=True)),
                ('isbn13', models.IntegerField(blank=True, null=True)),
                ('original_publication_year', models.IntegerField(blank=True, null=True)),
                ('original_title', models.CharField(blank=True, max_length=50)),
                ('language_code', models.CharField(blank=True, max_length=20)),
                ('image_url', models.CharField(blank=True, max_length=100)),
                ('small_image_url', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.Library')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='library',
            field=models.ManyToManyField(blank=True, through='books.BookLibrary', to='library.Library', verbose_name='Librería'),
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(blank=True, to='tags.Tag', verbose_name='Género'),
        ),
    ]
