# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-07-12 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200712_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, to='genres.Genres', verbose_name='Género'),
        ),
    ]
