# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-07-16 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200716_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=400, verbose_name='Título'),
        ),
    ]
