# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-07-16 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200716_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.CharField(blank=True, max_length=300, verbose_name='Autor'),
        ),
    ]
