# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-07-16 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200716_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language_code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
