# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-07-12 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0004_auto_20200712_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=20, verbose_name='Autor de la reseña')),
                ('text', models.CharField(blank=True, max_length=200, verbose_name='Texto')),
                ('stars', models.IntegerField(blank=True, choices=[(1, 'Muy malo'), (2, 'Malo'), (3, 'Normal'), (4, 'Bueno'), (5, 'Muy bueno')], null=True, verbose_name='Estrellas')),
                ('books', models.ManyToManyField(blank=True, to='books.Book', verbose_name='Libro')),
            ],
        ),
    ]
