# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-07-12 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(blank=True, choices=[(1, 'Muy malo'), (2, 'Malo'), (3, 'Normal'), (4, 'Bueno'), (5, 'Muy bueno')], null=True, verbose_name='Valoración'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='Autor de la reseña'),
        ),
    ]
