# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-07-12 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200712_2251'),
        ('reviews', '0002_auto_20200712_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='books',
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='Libro'),
            preserve_default=False,
        ),
    ]
